package fr.lbroquet.fatchains.swing;

import fr.lbroquet.fatchains.Partition;
import java.io.IOException;
import java.nio.file.Path;
import javax.swing.table.TableModel;

public class MainFrame extends javax.swing.JFrame {

    private final Partition partition;
    private final TableModel tableModel;

    public MainFrame(Path path) throws IOException {
        this.partition = new Partition(path);
        this.tableModel = new FatTableModel(partition);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel centerPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
        fatTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FAT Table");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        centerPanel.setLayout(new java.awt.BorderLayout());

        fatTable.setAutoCreateRowSorter(true);
        fatTable.setModel(tableModel);
        scrollPane.setViewportView(fatTable);

        centerPanel.add(scrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            partition.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fatTable;
    // End of variables declaration//GEN-END:variables
}
