package fr.lbroquet.fatchains.swing;

import fr.lbroquet.fatchains.Partition;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.nio.file.Path;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.table.TableModel;
import javax.swing.tree.TreeModel;

public class MainFrame extends javax.swing.JFrame {

    private final Partition partition;
    private final TableModel fatTableModel;
    private final TreeModel directoryTreeModel;
    private final Action fatAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            updateCenterPanel(fatTable);
        }
    };
    private final Action dirsAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            updateCenterPanel(directoryTree);
        }
    };

    public MainFrame(Path path) throws IOException {
        this.partition = new Partition(path);
        this.fatTableModel = new FatTableModel(partition.getEntryChains());
        this.directoryTreeModel = new DirectoryTreeModel(partition);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fatTable = new javax.swing.JTable();
        directoryTree = new javax.swing.JTree();
        javax.swing.JToolBar mainToolBar = new javax.swing.JToolBar();
        javax.swing.JButton fatButton = new javax.swing.JButton();
        javax.swing.JButton directoryButton = new javax.swing.JButton();
        javax.swing.JPanel centerPanel = new javax.swing.JPanel();
        centerScroll = new javax.swing.JScrollPane();

        fatTable.setAutoCreateRowSorter(true);
        fatTable.setModel(fatTableModel);

        directoryTree.setModel(directoryTreeModel);
        directoryTree.setRootVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FAT Table");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainToolBar.setRollover(true);

        fatButton.setAction(fatAction);
        fatButton.setText("FAT");
        fatButton.setFocusable(false);
        fatButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fatButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(fatButton);

        directoryButton.setAction(dirsAction);
        directoryButton.setText("DIRs");
        directoryButton.setFocusable(false);
        directoryButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        directoryButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(directoryButton);

        getContentPane().add(mainToolBar, java.awt.BorderLayout.PAGE_START);

        centerPanel.setLayout(new java.awt.BorderLayout());
        centerPanel.add(centerScroll, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            partition.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void updateCenterPanel(JComponent panel) {
        centerScroll.setViewportView(panel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane centerScroll;
    private javax.swing.JTree directoryTree;
    private javax.swing.JTable fatTable;
    // End of variables declaration//GEN-END:variables
}
